### PR TITLE
Add aayushdutt/modrinth-collection-downloader

### PR DESCRIPTION
**Pull request by aayushdutt**
Adds `aayushdutt/modrinth-collection-downloader` - a script to manage (download/update) mods from a modrinth collection

### CODE REVIEW

**Comment by aayushdutt** [comment]
@triphora created this addition, would you be able to take a look?

**Comment by triphora** [comment]
Negative, I am no longer a maintainer of this repository. @Geometrically

**Comment by aayushdutt** [comment]
@Geometrically would you be able to take a look?
Also, if this project needs help in maintenance, I'd be happy to help.

**Comment by aayushdutt** [comment]
Bumping this @Geometrically

**Comment by aayushdutt** [comment]
Bumping this PR @Geometrically

**Comment by blryface** [comment]
Oh god

**Comment by brawaru** [comment]
@Geometrically please don't bump anything, this is rude. You are essentially saying ‘I don't care what you are doing right now, I don't care if others are waiting as well, drop everything and review my PR **now**’. There's no need in that. Your PR will be reviewed and perhaps merged once time comes for it!

**Comment by aayushdutt** [comment]
I'm sorry I didn't mean to be rude. I was not sure if this being looked at by anyone because of the lack of any acknowledgement.
Thanks for confirming that it'll be reviewed when the time comes!

**Comment by aayushdutt** [comment]
Also wondering if you feel there is any way to improve this repository's situation.
As this is a community `awesome` repository, it shouldn't ideally have `single line` PRs open since last 4 months without any acknowledgement.

**Comment by blryface** [comment]
it's probably because modrinth has other priorities right now

**Comment by aayushdutt** [comment]
Are you open to adding more maintainers to help with maintaining this repository? I'm sure many other contributors, including myself, will be happy to help.

**Comment by blryface** [comment]
h

**Pull request merged**
