### PR TITLE
add tympanicblock61/modrinth-downloader

### PR DESCRIPTION
**Pull request by tympanicblock61**

### CODE REVIEW

**Review by triphora — CHANGES_REQUESTED** [review]
Alphabetical order please

**Comment by tympanicblock61** [comment]
> Alphabetical order please

changed

**Comment by arlomcwalter** [comment]
am i wrong in thinking that this repo does not exist or at least isn't public

**Review by triphora — CHANGES_REQUESTED** [review]
Yeah, it appears to be private. Please make it public if you want it to be on the list.

**Comment by tympanicblock61** [comment]
> am i wrong in thinking that this repo does not exist or at least isn't public

Did I seriously fucking forget to public it 💀

**Comment by tympanicblock61** [comment]
> Yeah, it appears to be private. Please make it public if you want it to be on the list.

Fixed

**Pull request merged**
